include:
  - docker-compose.dagster.yml
  - docker-compose.lakekeeper.yml
  - docker-compose.spark.yml
services:
  default-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./common/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres -h localhost"]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  db_data:
